development:
  adapter: postgresql
  encoding: unicode
  database: pizza_dev
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: pizza_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: PizzaApp
  pool: 5
  username:
  password:
